# Generated by Django 5.0.4 on 2024-04-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('authorization_code', models.CharField(blank=True, max_length=4, null=True)),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
